#!/usr/bin/env python3
from helpers import get_user_timeline
from analyzer import Analyzer
import os
import sys
from termcolor import colored

# TODO
def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("-1")
    tweets=get_user_timeline(sys.argv[1], 50)
    if(tweets==None):
        sys.exit("2")
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # analyze tweet
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("1 "+tweet, "green"))
        elif score < 0.0:
            print(colored("-1 "+tweet, "red"))
        else:
            print(colored("0 "+tweet, "yellow"))
    
if __name__ == "__main__":
    main()
